<?php

/**
 * allows for service container parameters inside databases.yml
 *
 * @package    sfServiceContainerPlugin
 * @author     Brent Shaffer <bshafs@gmail.com>
 */
class ServiceContainer_FactoryConfigHandler extends sfFactoryConfigHandler
{
  /**
   * Executes this configuration handler.
   *
   * @param array $configFiles An array of absolute filesystem path to a configuration file
   *
   * @return string Data to be written to a cache file
   *
   * @throws sfConfigurationException If a requested configuration file does not exist or is not readable
   * @throws sfParseException If a requested configuration file is improperly formatted
   */
  public function execute($configFiles)
  {
    $data = parent::execute($configFiles);
    
    if (!sfContext::hasInstance()) {
        throw new sfFactoryException('Cannot parse factories.yml - no sfContext instance');
    }

    if (($context = sfContext::getInstance()) instanceof ServiceContainer_Context) {
        $context->loadContainer();
        $data = $context->getContainer()->resolveValue($data);
    }

    // replace top comment
    $data = str_replace('auto-generated by sfFactoryConfigHandler', 'auto-generated by ServiceContainer_FactoryConfigHandler', $data);

    return $data;
  }
}
